version: '3.8'

services:
  credit-scoring-service:
    build:
      context: ./credit-scoring-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./credit-scoring-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
