name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker compose up
      run: |
        docker compose up -d --build

    - name: sleep
      run: |
        sleep 10

    - name: tests
      run: |
        docker compose exec credit-scoring-service pytest tests/

    - name: Docker compose down
      if: always()
      run: |
        docker-compose down